### ISSUE TITLE
ModuleNotFoundError: No module named 'comfy_trt'

### ISSUE THREAD

**Issue by xshinoryu** [phineas-pta/comfy-trt-test#2]
Hey there!
So I've tried to install it all on portable comfyui with python_embeded python.exe, and when I try to interract with convert_unet.py, it always keeps saying ModuleNotFoundError: No module named 'comfy_trt', which is, well, weird...

C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable>python_embeded\python.exe ComfyUI\custom_nodes\comfy-trt-test\convert_unet.py --help
Traceback (most recent call last):
  File "C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-trt-test\convert_unet.py", line 13, in <module>
    from comfy_trt.exporter import export_onnx, export_trt
ModuleNotFoundError: No module named 'comfy_trt'

Yet the nodes themselves are there, and there aren't any mistakes in the console...

**Comment by phineas-pta** [comment]
u have to navigate console to folder `comfy-trt-test` before calling `convert_unet.py`

**Comment by Natotela** [comment]
Getting the same issue, following instructions (installed according to the "alternatively:" pip install --pre tensorrt==9.0.1.post11.dev4 --extra-index-url https://pypi.nvidia.com --no-cache-dir)

```
 F:\Progz\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-trt-test> F:\Progz\ComfyUI_windows_portable\python_embeded\python.exe convert_unet.py --help
Traceback (most recent call last):
  File "F:\Progz\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-trt-test\convert_unet.py", line 13, in <module>
    from comfy_trt.exporter import export_onnx, export_trt
ModuleNotFoundError: No module named 'comfy_trt'
```

[[ xshinoryu is right calling the folder comfyui BLYAT :-D  ]]

**Comment by phineas-pta** [comment]
there's a folder `comfy_trt` inside `comfy-trt-test` ?

**Comment by Artleksandr** [comment]
Same issue
> there's a folder `comfy_trt` inside `comfy-trt-test` ?
the folder is there
![image](https://github.com/phineas-pta/comfy-trt-test/assets/60533582/0feda743-3d55-49ca-92a8-e2c921d66b08)

**Comment by Artleksandr** [comment]
copying comfy_trt to site-packages seems to solve the problem

**Comment by phineas-pta** [comment]
> copying comfy_trt to site-packages seems to solve the problem

yes but it isn't a good solution: u cannot receive update with git

can u try calling python with relative path instead of absolute path ?

**Comment by Artleksandr** [comment]
> can u try calling python with relative path instead of absolute path ?

![image](https://github.com/phineas-pta/comfy-trt-test/assets/60533582/f693703e-8f12-409f-94d7-1e5e6857945e)

**Comment by phineas-pta** [comment]
sr im clueless

well actually i have a workaround in mind but tbh it's ugly and im avoiding it at all cost 🫣

```python
import sys
sys.path.append(".")
```

**Comment by QuackAstra** [comment]
Add these folders to PATH (in System Variables): 
C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable>python_embeded\
C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable>python_embeded\Scripts



move it all the way up

go to C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-trt-test\

python convert_unet.py --help


note that this will mess with your normal python installation, so move the PATH entries back down in the list when you're done.
