### ISSUE TITLE
Cannot Build the Unet Model -Help

### ISSUE THREAD

**Issue by Piscabo** [phineas-pta/comfy-trt-test#5]
`python convert_unet.py --ckpt_path "H:\ComfyUI\models\checkpoints\SDXL\turbovisionxlSuperFastXL_tvxlV431vae.safetensors" --batch_max 4 --height_min 512 --width_min 512 --height_max 1024 --width_max 1024 --token_count_max 300`

 warnings.warn(warning)
ERROR:root:Exporting to ONNX failed. ONNX export failed on an operator with unrecognized namespace xformers_flash::flash_fwd. If you are trying to export a custom operator, make sure you registered it with the right domain and version.
Building TensorRT engine… This can take a while.
Building TensorRT engine for H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\sd_xl_turbo_1.0_fp16.onnx: H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-trt\sd_xl_turbo_1.0_fp16_1a54828ff58cb83ba8972aa17e71bd66.trt
Could not open file H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\sd_xl_turbo_1.0_fp16.onnx
Could not open file H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\sd_xl_turbo_1.0_fp16.onnx
[E] ModelImporter.cpp:773: Failed to parse ONNX model from file: H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\sd_xl_turbo_1.0_fp16.onnx
[!] Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?

**Comment by phineas-pta** [comment]
u r sure about that console message output ? the input model is `turbovisionxlSuperFastXL_tvxlV431vae.safetensors` but the message is about `sd_xl_turbo_1.0_fp16`

**Comment by Piscabo** [comment]
Same message. Sorry was so tired. Tried different turbo models, with the same result.
Building TensorRT engine for H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\sd_xl_turbo_1.0_fp16.onnx: H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-trt\sd_xl_turbo_1.0_fp16_1a54828ff58cb83ba8972aa17e71bd66.trt
Could not open file H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\sd_xl_turbo_1.0_fp16.onnx
Could not open file H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\sd_xl_turbo_1.0_fp16.onnx
_[E] ModelImporter.cpp:773: Failed to parse ONNX model from file: H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\sd_xl_turbo_1.0_fp16.onnx
[!] Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?_
Traceback (most recent call last):
  File "H:\ComfyUI\custom_nodes\comfy-trt-test\convert_unet.py", line 141, in <module>
    ret = export_trt(trt_path, onnx_path, timing_cache, profile=profile, use_fp16=not args.float32)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ret = engine.build(onnx_path, use_fp16, enable_refit=True, timing_cache=timing_cache, input_profile=[profile])                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\utilities.py", line 151, in build
    network = network_from_onnx_path(onnx_path, flags=[trt.OnnxParserFlag.NATIVE_INSTANCENORM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in network_from_onnx_path
  File "C:\comfyVENV\Lib\site-packages\polygraphy\backend\base\loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyVENV\Lib\site-packages\polygraphy\util\util.py", line 710, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyVENV\Lib\site-packages\polygraphy\backend\trt\loader.py", line 227, in call_impl
    trt_util.check_onnx_parser_errors(parser, success)
  File "C:\comfyVENV\Lib\site-packages\polygraphy\backend\trt\util.py", line 86, in check_onnx_parser_errors
    G_LOGGER.critical("Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?")
  File "C:\comfyVENV\Lib\site-packages\polygraphy\logger\logger.py", line 605, in critical
    raise ExceptionType(message) from None
polygraphy.exception.exception.PolygraphyException: Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?

**Comment by phineas-pta** [comment]
seem like problem with turbo, u may want to try other models not turbo, there's already another problem with turbo in #4

i may need to remove turbo from supported list

**Comment by phineas-pta** [comment]
what onnx version and tensorrt version u have ?

**Comment by Piscabo** [comment]
> what onnx version and tensorrt version u have ?
![image](https://github.com/phineas-pta/comfy-trt-test/assets/123719842/58b8f5f0-9c0e-4ec8-a912-4c56376ca040)
![image](https://github.com/phineas-pta/comfy-trt-test/assets/123719842/41063904-0c1e-474a-9275-cfce3457882e)

**Comment by Piscabo** [comment]
No luck with other SDXL Models.
C:\comfyVENV\Lib\site-packages\torch\onnx\utils.py:737: UserWarning: We detected that you are modifying a dictionary that is an input to your model. Note that dictionaries are allowed as inputs in ONNX but they should be handled with care. Usages of dictionaries is not recommended, and should not be used except for configuration use. Also note that the order and values of the keys must remain the same.
  warnings.warn(warning)
ERROR:root:Exporting to ONNX failed. ONNX export failed on an operator with unrecognized namespace xformers_flash::flash_fwd. If you are trying to export a custom operator, make sure you registered it with the right domain and version.
ONNX file has been saved to disk.
H:\ComfyUI\custom_nodes\comfy-trt-test\..\..\comfy\ldm\modules\diffusionmodules\openaimodel.py:844: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert y.shape[0] == x.shape[0]
ERROR:root:Exporting to ONNX failed. ONNX export failed on an operator with unrecognized namespace xformers_flash::flash_fwd. If you are trying to export a custom operator, make sure you registered it with the right domain and version.
Building TensorRT engine… This can take a while.
Building TensorRT engine for H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\albedobaseXL_v20.onnx: H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-trt\albedobaseXL_v20_1a54828ff58cb83ba8972aa17e71bd66.trt
Could not open file H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\albedobaseXL_v20.onnx
Could not open file H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\albedobaseXL_v20.onnx
[E] ModelImporter.cpp:773: Failed to parse ONNX model from file: H:\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\albedobaseXL_v20.onnx
[!] Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?

**Comment by phineas-pta** [comment]
it's weird ... i cannot reproduce those error 

u have enough vram and/or disk space ?

**Comment by Piscabo** [comment]
> it's weird ... i cannot reproduce those error
> 
> u have enough vram and/or disk space ?

RTX 3060 12GB - 200GB open space of 1TB, 32GB Ram

**Comment by phineas-pta** [comment]
if u dont mind can u delete 2 folders `Unet-onnx` & `Unet-trt` then try convert again ?

for any SDXL model it should create 2 files: 1 `.onnx` file 3 MB + 1 file without extension 5.2 GB

**Comment by Piscabo** [comment]
Did that and I now have a new install, but I still have this problem. I so want to experiment with this... :-(

C:\AI_Files\venv\Lib\site-packages\torch\onnx\utils.py:737: UserWarning: We detected that you are modifying a dictionary that is an input to your model. Note that dictionaries are allowed as inputs in ONNX but they should be handled with care. Usages of dictionaries is not recommended, and should not be used except for configuration use. Also note that the order and values of the keys must remain the same.
  warnings.warn(warning)
ERROR:root:Exporting to ONNX failed. ONNX export failed on an operator with unrecognized namespace xformers_flash::flash_fwd. If you are trying to export a custom operator, make sure you registered it with the right domain and version.
Building TensorRT engine… This can take a while.
Building TensorRT engine for C:\AI_Files\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\RealVisXLv20_VAE.onnx: C:\AI_Files\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-trt\RealVisXLv20_VAE_1a54828ff58cb83ba8972aa17e71bd66.trt
Could not open file C:\AI_Files\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\RealVisXLv20_VAE.onnx
Could not open file C:\AI_Files\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\RealVisXLv20_VAE.onnx
[E] ModelImporter.cpp:844: Failed to parse ONNX model from file: C:\AI_Files\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\RealVisXLv20_VAE.onnx
[!] Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?
Traceback (most recent call last):
  File "C:\AI_Files\ComfyUI\custom_nodes\comfy-trt-test\convert_unet.py", line 141, in <module>
    ret = export_trt(trt_path, onnx_path, timing_cache, profile=profile, use_fp16=not args.float32)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Files\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\exporter.py", line 157, in export_trt
    ret = engine.build(onnx_path, use_fp16, enable_refit=True, timing_cache=timing_cache, input_profile=[profile])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Files\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\utilities.py", line 151, in build
    network = network_from_onnx_path(onnx_path, flags=[trt.OnnxParserFlag.NATIVE_INSTANCENORM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in network_from_onnx_path
  File "C:\AI_Files\venv\Lib\site-packages\polygraphy\backend\base\loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Files\venv\Lib\site-packages\polygraphy\util\util.py", line 710, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Files\venv\Lib\site-packages\polygraphy\backend\trt\loader.py", line 227, in call_impl
    trt_util.check_onnx_parser_errors(parser, success)
  File "C:\AI_Files\venv\Lib\site-packages\polygraphy\backend\trt\util.py", line 86, in check_onnx_parser_errors
    G_LOGGER.critical("Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?")
  File "C:\AI_Files\venv\Lib\site-packages\polygraphy\logger\logger.py", line 605, in critical
    raise ExceptionType(message) from None
polygraphy.exception.exception.PolygraphyException: Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?

**Comment by phineas-pta** [comment]
do u see any onnx file as i said ?

**Comment by Piscabo** [comment]
> do u see any onnx file as i said ?

I do follow your instructions. I first deleted those folders... Nothing gets created in ONNX
![image](https://github.com/phineas-pta/comfy-trt-test/assets/123719842/075d4e43-57b4-4ce3-bdaf-c76493001d67)
But in unet-TRT
![image](https://github.com/phineas-pta/comfy-trt-test/assets/123719842/06018938-bf76-48fc-bc1c-ff2570ba9499)

**Comment by phineas-pta** [comment]
no onnx file at all 😰

seem like something mess up with `xformers` ...

if there is nothing rely on `xformers` can u try remove it ? comfyui doesnt rely on it anymore

**Comment by Piscabo** [comment]
I removed xformers now I can create files, but they fail:
Building TensorRT engine… This can take a while.
Building TensorRT engine for C:\AI_Files\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\sd_xl_base_1.0_0.9vae.onnx: C:\AI_Files\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-trt\sd_xl_base_1.0_0.9vae_1a54828ff58cb83ba8972aa17e71bd66.trt
**_[E] 1: [stdArchiveReader.cpp::nvinfer1::rt::StdArchiveReader::stdArchiveReaderInitCommon::47] Error Code 1: Serialization (Serialization assertion stdVersionRead == kSERIALIZATION_VERSION failed.Version tag does not match. Note: Current Version: 228, Serialized Engine Version: 224)
[E] 4: The timing cache will not be used!
[E] 1: [stdArchiveReader.cpp::nvinfer1::rt::StdArchiveReader::stdArchiveReaderInitCommon::47] Error Code 1: Serialization (Serialization assertion stdVersionRead == kSERIALIZATION_VERSION failed.Version tag does not match. Note: Current Version: 228, Serialized Engine Version: 224)
[E] 4: The timing cache will not be used!_**
TensorRT engines has been saved to disk.

**Comment by phineas-pta** [comment]
> TensorRT engines has been saved to disk.

it worked 😉 now u can check if the engine actually work in comfyui

**Comment by Piscabo** [comment]
> > TensorRT engines has been saved to disk.
> 
> it worked 😉 now u can check if the engine actually work in comfyui

But what does that error mean?
[E] 1: [stdArchiveReader.cpp::nvinfer1::rt::StdArchiveReader::stdArchiveReaderInitCommon::47] Error Code 1: Serialization (Serialization assertion stdVersionRead == kSERIALIZATION_VERSION failed.Version tag does not match. Note: Current Version: 228, Serialized Engine Version: 224)
[E] 4: The timing cache will not be used!
[E] 1: [stdArchiveReader.cpp::nvinfer1::rt::StdArchiveReader::stdArchiveReaderInitCommon::47] Error Code 1: Serialization (Serialization assertion stdVersionRead == kSERIALIZATION_VERSION failed.Version tag does not match. Note: Current Version: 228, Serialized Engine Version: 224)
[E] 4: The timing cache will not be used!

**Comment by phineas-pta** [comment]
doesnt matter if the trt engine works, i already said in README

**Comment by Piscabo** [comment]
> doesnt matter if the trt engine works, i already said in README

Fails in Comfy Generation: 
![image](https://github.com/phineas-pta/comfy-trt-test/assets/123719842/fbb4df37-3cd4-481b-8ffd-d41d22b216ff)

**Comment by phineas-pta** [comment]
seem like comfyui update something

wait a sec

**Comment by phineas-pta** [comment]
i just push an update, can u try ?

**Comment by Piscabo** [comment]
Thanks for the help. Think the previous error is gone but now I get this:
![image](https://github.com/phineas-pta/comfy-trt-test/assets/123719842/4c3efbf1-f54d-4691-979e-5a4d8c853863)
![image](https://github.com/phineas-pta/comfy-trt-test/assets/123719842/daf9838b-a785-45ea-8e0b-b63d9d2ba9aa)
Dont you have a preset workflow I can try?

**Comment by phineas-pta** [comment]
as i said: turbo has problem

u can try other xl models

**Comment by al-swaiti** [comment]
![image](https://github.com/phineas-pta/comfy-trt-test/assets/95714669/9a083ff1-749d-4d58-9c15-517b6f7d9db8)
i created two model one normal and one sdxl turbo both give me this error any idea ,,,

**Comment by al-swaiti** [comment]
![image](https://github.com/phineas-pta/comfy-trt-test/assets/95714669/d9c57f6c-1361-466f-bffb-74a345089565)

**Comment by al-swaiti** [comment]
Also I tried all --fpxx-unet options

**Comment by phineas-pta** [comment]
- don't hijack issue if u dont have same error
- turbo has a different workflow, what model u using when u get those errors ?
- make sure to have a proper setup and well isolated, and give proper bug report, i only see a mess:
  - different nodes in error message eventhough there's no custom node in your workflow image
  - weird model name, seem like image output, what is it ? if that's something private, i cannot test it i cannot help
  - u use a1111 and comfyui in same venv

**Comment by al-swaiti** [comment]
i think its same error but you couldn't get the point ,,, i tried to make the onyx file using stable diffusion extinsion  with turbo model and its work perfect using your node , so the problem in converting onyx files in your code

**Comment by phineas-pta** [comment]
u think ? do u bother to compare error message u having vs error message in this issue ? also could u address other points i made above ?

**Comment by al-swaiti** [comment]
i was have same error okay so i follow the you !

**Comment by al-swaiti** [comment]
until i face that error ,,

**Comment by al-swaiti** [comment]
and i think its okay if i have same env for any if they need same library is that right

**Comment by phineas-pta** [comment]
> and i think its okay if i have same env for any if they need same library is that right

no, i have no idea how u setup a1111 and whether it's the same as comfyui

again could u address other points i made above ?

**Comment by al-swaiti** [comment]
Thank you you are amazing ,,,
