### ISSUE TITLE
Dimension Error with SDXL models with batch size max > 1

### ISSUE THREAD

**Issue by Tliks** [phineas-pta/comfy-trt-test#7]
Thank you for your work on this project

This error occurs during image generation using a converted model. It does not occur with SD 1.5 models but has been observed in two different SDXL models. The error appears when using models converted with a specified batch size; it does not manifest in models converted without specifying the batch size.

tensorrt == 9.2.0.post12.dev

```
[E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2069] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2069, condition: profileMinDims.d[i] <= dimensions.d[i] Supplied binding dimension [-1,2816] for bindings[3] exceed min ~ max range at index 0, maximum dimension in profile is 8, minimum dimension in profile is 1, but supplied dimension is -1.)
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\doc\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\doc\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\doc\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\doc\ComfyUI\nodes.py", line 1355, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "C:\doc\ComfyUI\nodes.py", line 1325, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "C:\doc\ComfyUI\comfy\sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\doc\ComfyUI\comfy\samplers.py", line 716, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\doc\ComfyUI\comfy\samplers.py", line 622, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "C:\doc\ComfyUI\comfy\samplers.py", line 561, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "C:\doc\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\doc\ComfyUI\comfy\k_diffusion\sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "C:\doc\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\doc\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\doc\ComfyUI\comfy\samplers.py", line 285, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
  File "C:\doc\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\doc\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\doc\ComfyUI\comfy\samplers.py", line 275, in forward
    return self.apply_model(*args, **kwargs)
  File "C:\doc\ComfyUI\comfy\samplers.py", line 272, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "C:\doc\ComfyUI\comfy\samplers.py", line 252, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "C:\doc\ComfyUI\comfy\samplers.py", line 226, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "C:\doc\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\node_unet.py", line 148, in apply_model
    model_output = self.diffusion_model.forward(x=xc, timesteps=t, context=context, **extra_conds).float()
  File "C:\doc\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\node_unet.py", line 207, in forward
    self.engine.allocate_buffers(feed_dict)
  File "C:\doc\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\utilities.py", line 212, in allocate_buffers
    tensor = torch.empty(tuple(shape), dtype=numpy_to_torch_dtype_dict[dtype]).to(device=device)
RuntimeError: Trying to create tensor with negative dimension -1: [-1, 2816]
```

**Comment by phineas-pta** [comment]
if possible can u provide more info:
- what model
- parameters when u convert
- parameters when u generate images

**Comment by Tliks** [comment]
![スクリーンショット 2024-01-15 192353](https://github.com/phineas-pta/comfy-trt-test/assets/127580611/68c39b50-6f52-4cac-a18f-01a853c4ca42)
- Animagine XL V3 and Counterfeit XL v10
- --batch_max 4
- 1024x1024 batch_size 1

I tried changing various parameters during both the conversion and image generation processes, but the result remained the same



Additionally, there was an error message during conversion that might be relevant to this issue
```
C:\doc\ComfyUI\custom_nodes\comfy-trt-test\..\..\comfy\ldm\modules\diffusionmodules\openaimodel.py:844: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert y.shape[0] == x.shape[0]
C:\doc\ComfyUI\custom_nodes\comfy-trt-test\..\..\comfy\ldm\modules\diffusionmodules\openaimodel.py:125: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1] == self.channels
C:\doc\ComfyUI\custom_nodes\comfy-trt-test\..\..\comfy\ldm\modules\diffusionmodules\openaimodel.py:125: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1] == self.channels
C:\doc\ComfyUI\custom_nodes\comfy-trt-test\..\..\comfy\ldm\modules\diffusionmodules\openaimodel.py:83: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1] == self.channels
C:\doc\ComfyUI\venv\lib\site-packages\torch\onnx\utils.py:737: UserWarning: We detected that you are modifying a dictionary that is an input to your model. Note that dictionaries are allowed as inputs in ONNX but they should be handled with care. Usages of dictionaries is not recommended, and should not be used except for configuration use. Also note that the order and values of the keys must remain the same.
  warnings.warn(warning)
Building TensorRT engine… This can take a while.
Building TensorRT engine for C:\doc\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-onnx\animagine-xl-3.0.onnx: C:\doc\ComfyUI\custom_nodes\comfy-trt-test\comfy_trt\Unet-trt\animagine-xl-3.0_dc608e0599e062ec71561b8b8adb104a.trt
[E] 1: [stdArchiveReader.cpp::nvinfer1::rt::StdArchiveReader::stdArchiveReaderInitCommon::47] Error Code 1: Serialization (Serialization assertion stdVersionRead == kSERIALIZATION_VERSION failed.Version tag does not match. Note: Current Version: 228, Serialized Engine Version: 224)
[E] 4: The timing cache will not be used!
```

**Comment by phineas-pta** [comment]
im very sorry but i dont have a gpu that can run sdxl at batch size >1 to test it 😢😢😢

**Comment by arthursunbao** [comment]
I have the same issue, it seems that it lacks the parameter y from node.unet.py, line 204.

@phineas-pta Can you kindly help to share your snapshot for SDXL pipeline?  I don't know if I setup the pipeline right or not, I cannot get SDXL pipeline running

**Comment by phineas-pta** [comment]
u can just use a normal sdxl workflow (or even the comfyui default workflow), only change is to connect trt engine to ksampler
