### ISSUE TITLE
Unable to run convert_unet.py

### ISSUE THREAD

**Issue by dotada** [phineas-pta/comfy-trt-test#9]
Running on native win 11, I installed tensorrt 9 as well as cuda toolkit and cuDNN as per the linked guide but whenever I try running ```python .\convert_unet.py --ckpt_path ./anythingv5.safetensors``` I always get the error 
```xformers version: 0.0.24
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
VAE dtype: torch.bfloat16
Using xformers cross attention
Traceback (most recent call last):
  File "E:\StabilityMatrix-win-x64\data\Packages\ComfyUI\custom_nodes\comfy-trt-test\convert_unet.py", line 71, in <module>
    ckpt_config = get_config_from_checkpoint(args.ckpt_path)
  File "E:\StabilityMatrix-win-x64\data\Packages\ComfyUI\custom_nodes\comfy-trt-test\convert_unet.py", line 53, in get_config_from_checkpoint
    unet_config = detect_unet_config(sd, tmp0, unet_dtype)
TypeError: detect_unet_config() takes 2 positional arguments but 3 were given
```
I tried reinstalling multiple times but nothing happened. Any help would be much appreciated!

**Comment by phineas-pta** [comment]
holy hell comfy change the way to do things, i need to update

i cannot give a time estimate, i'll ping u when i finish

**Comment by dotada** [comment]
> holy hell comfy change the way to do things, i need to update
> 
> i cannot give a time estimate, i'll ping u when i finish

No problem! Being a self taught programmer I know how painful some updates can be. Thanks for your attention.

**Comment by dotada** [comment]
@phineas-pta When building I got the error
```
[E] Module: 'onnx_graphsurgeon' version '0.3.12' is installed, but version '>=0.3.27' is required.
    Please install the required version or set POLYGRAPHY_AUTOINSTALL_DEPS=1 in your environment variables to allow Polygraphy to do so automatically.
    Attempting to continue with the currently installed version of this module, but note that this may cause errors!
```
But I let it continue and eventually it errored out with 
```
[E] 10: Could not find any implementation for node {ForeignNode[(Unnamed Layer* 1610) [Cast].../input_blocks.4.1/Reshape_1 + /input_blocks.4.1/Transpose_1]}.
[E] 10: [optimizer.cpp::nvinfer1::builder::cgraph::LeafCNode::computeCosts::4048] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[(Unnamed Layer* 1610) [Cast].../input_blocks.4.1/Reshape_1 + /input_blocks.4.1/Transpose_1]}.)
[!] Invalid Engine. Please ensure the engine was built correctly
ERROR:root:Failed to build engine: Invalid Engine. Please ensure the engine was built correctly
Export Failed due to unknown reason.
```

**Comment by dotada** [comment]
ok disregard the above comment, I'm a dumbass and thought setting 2048 as max width and height was a good idea. setting them at 1024 did it and the tensorRT engine built successfully
